# Generated by Django 4.2.7 on 2023-11-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('availability', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(choices=[('Backend Developer', 'Be Developer'), ('Frontend Developer', 'Fe Developer'), ('DevOps', 'Devops')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Freelancers',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
