# Generated by Django 4.2.7 on 2023-11-23 16:53

from django.db import migrations, models
import freelancer.models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_freelancer_delete_freelancers_delete_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='availability',
            field=models.CharField(blank=True, max_length=255, validators=[freelancer.models.Validator.validate_availability]),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='email',
            field=models.CharField(blank=True, max_length=255, validators=[freelancer.models.Validator.validate_email]),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='name',
            field=models.CharField(blank=True, max_length=255, validators=[freelancer.models.Validator.validate_name]),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, validators=[freelancer.models.Validator.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='position',
            field=models.CharField(choices=[('Backend Developer', 'Be Developer'), ('Frontend Developer', 'Fe Developer'), ('DevOps', 'Devops')], max_length=255, validators=[freelancer.models.Validator.validate_position]),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='salary',
            field=models.CharField(blank=True, max_length=255, validators=[freelancer.models.Validator.validate_salary]),
        ),
    ]
