# Generated by Django 4.2.7 on 2023-11-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_alter_freelancer_availability_alter_freelancer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='availability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='salary',
            field=models.FloatField(),
        ),
    ]
